name: Deploy Prexixion API

on:
  workflow_dispatch:

jobs:
  build:
    name: Build API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compilar aplicación
        run: mvn clean package

      - name: Guardar JAR
        uses: actions/upload-artifact@v4
        with:
          name: prexixion-api-jar
          path: target/PrexixionApi-0.0.1-SNAPSHOT.jar


  deploy:
    name: Deploy API
    needs: build
    runs-on:
      - self-hosted
      - deploy

    steps:
      - name: Descargar JAR
        uses: actions/download-artifact@v4
        with:
          name: prexixion-api-jar

      - name: Desplegar API
        run: |
          echo "Copiando nueva versión..."
          cp PrexixionApi-0.0.1-SNAPSHOT.jar /opt/api/PrexixionApi-0.0.1-SNAPSHOT.jar

      - name: Diagnóstico runner
        run: |
          echo "Usuario:"
          whoami

          echo "PATH:"
          echo $PATH

          echo "Systemctl:"
          which systemctl

          echo "Sudo permisos:"
          sudo -l

          echo "Reiniciando servicio..."
          sudo /usr/bin/systemctl restart api.service

          echo "Servicio reiniciado correctamente"